[package]
name = "envelop"
version = "0.0.0"
authors = ["Jake Swenson <jake@jakeswenson.com>"]
edition = "2018"
description = "An envelope encryption library porting godaddy/asherah to rust"
license-file = "LICENSE"

[dependencies]
